version: '3.7'

services:
  delta_backend:
    container_name: delta_backend
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - './backend:/app'
    ports:
      - '8080:8080'

  delta_frontend:
    container_name: delta_frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

  redis:
    image: redis:5
    container_name: delta_cache
    expose:
      - 6379
    ports:
      - '6379:6379'

  db:
      image: "postgres:12"
      container_name: delta_database
      environment:
        - POSTGRES_USER=delta
        - POSTGRES_PASSWORD=123123
        - POSTGRES_DB=delta_db
      ports:
        - '54320:5432'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
